### ISSUE TITLE
Get it a perfect domain name

### ISSUE THREAD

**Issue by b1f6c1c4** [tangx/Stop-Ask-Questions-The-Stupid-Ways#2]
A nice domain name, compared to a link for a github repo, will much more beneficial when someone else asks me stupid questions: I may simply send them links like [asking-questions.online](https://asking-questions.online/) or [ask-question.online](https://ask-question.online/) or etc. They'll be more likely to click such a short link than the super long link to Github. Further, there's no 'stop' nor 'stupid' shown in the URL, so they won't be intimidated and refuse to click the link.

You may purchase the domain from Godaddy:

https://www.godaddy.com/domainsearch/find?isc=GPPTCUST&checkAvail=1&tmskey=&domainToCheck=asking-questions.online

**Comment by tangx** [comment]
个人感觉没必要。
如果一个人不愿意正视自己的不足并加以改正，那么也就没有必要帮助他成长了。

以下是 github 短域名服务提供的快捷地址

```
https://git.io/how-to-asking

https://git.io/asking-question

https://git.io/stop-stupid
```
